### ISSUE TITLE
Roadmapping Talk - Content

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#1]
- [x] Review [short talk guidelines](https://github.com/mozillascience/learning/blob/master/talk-guidelines.md) 
- [x] Post a link to your outline here! For review and discussion. If you're just getting started, just link to wherever you're working.
- [x] @zee-moz review & discuss
- [x] Revise and Refine
- [ ] Create handout
- [x] Draft Slides in Google Slides

**Comment by abbycabs** [comment]
thanks @zee-moz!

in progress:
https://docs.google.com/a/mozilla.com/document/d/1pmqJFTdQGtizAbFiqFWLqB2L_Nk5106QPxRBquSiTAc/edit?usp=sharing

**Comment by abbycabs** [comment]
Updated the draft after your last round of comments, @zee-moz! Thanks :)

**Comment by abbycabs** [comment]
@zee-moz - I checked off '@zee-moz review & discuss' and 'Revise and Refine' -- not sure if you were done here, feel free to uncheck if you have more comments!

**Comment by abbycabs** [comment]
Template for creating the handout:
https://github.com/mozillascience/learning/blob/master/resource-template.md

**Comment by abbycabs** [comment]
Handout in this pull request!
https://github.com/mozillascience/working-open-workshop/pull/14

**Comment by abbycabs** [comment]
Slides:
https://docs.google.com/presentation/d/11y0MNj820ElX4m1LuDVekHoXMzxch1Zdlga12VHTNKU/edit?usp=sharing

**Comment by auremoser** [comment]
closing to make room for participant issues :)
