### ISSUE TITLE
Visual/Design Resources for MSL's Working Open Workshop

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#10]
Spoke with Cassie about this. Here's [the issue in the Mofo /plan repo](https://github.com/MozillaFoundation/plan/issues/679)
Next steps:
- [x] follow up with Cassie
- [x] provide content as needed
  ...

**Comment by flukeout** [comment]
Here's a template for the handouts...
https://github.com/mozillascience/learning/blob/master/resource-template.md

We'll start a wireframe using the content here...
https://public.etherpad-mozilla.org/p/WOW-personas-pathways-handout

**Comment by cassiemc** [comment]
Let's close this, I think the more granular issues are already represented in this repo. :)
