### ISSUE TITLE
Update handouts to use the new template!

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/working-open-workshop#17]
Create html handouts for:
- [x] Roadmapping
- [x] User Personas and Pathways
- [x] README
- [x] Contributor Guidelines
- [x] GitHub for newbies
- [x] Code of Conduct
- [x] Sprints and Events
- [x] Data Use and Reuse Plan
- [ ] more that I forgot..

owner: @zee-moz? (but pls assign as many as you like to me)

Steps to complete:
1. clone the repo & go on the gh-pages branch
   
   ```
   git clone git@github.com:mozillascience/working-open-workshop.git
   cd working-open-workshop
   git checkout gh-pages
   ```
   
   If you've already cloned the repo, use this to bring in new changes that may have occured:
   
   ```
   git fetch origin
   git merge origin/gh-pages
   ```
2. copy the template folder to a folder named with your lesson
   
   ```
   cp -r template/ YOUR_LESSON
   ```
3. Edit the `YOUR_LESSON/index.html` to include content for your lesson
   - Use  your favourite text editor
4. commit & push your changes to gh-pages
   
   ```
   git add YOUR_LESSON/
   git commit -m "Adding html version of the YOUR_LESSON handout"
   git push origin gh-pages
   ```

Your beautiful handout will now appear at:
http://mozillascience.github.io/working-open-workshop/YOUR_LESSON

Live template is here:
http://mozillascience.github.io/working-open-workshop/template

**Comment by stephwright** [comment]
Data Reuse Handout is live: http://mozillascience.github.io/working-open-workshop/data_reuse/

Issue w/ Glossary not wrapping.  Already raised the issue w/ @flukeout

**Comment by flukeout** [comment]
@stephwright - I fixed the issue in #18 - have a look at [the changes I made](https://github.com/mozillascience/working-open-workshop/pull/18/files) - we were just missing some markup around each of the terms. Once @acabunoc reviews, we'll be good to go.

**Comment by stephwright** [comment]
Awww... you fixed my lesson for me!  Thank you for doing that! Much appreciated.

**Comment by auremoser** [comment]
Well done errybody!

**githug**

![githug](http://i.giphy.com/JglVCaB0axZ4Y.gif)

**Comment by abbycabs** [comment]
:heart:
