### ISSUE TITLE
Readme Talk - Content

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#2]
- [x] Review [short talk guidelines](https://github.com/mozillascience/learning/blob/master/talk-guidelines.md) 
- [x] Post a link to your outline here! For review and discussion. If you're just getting started, just link to wherever you're working.
- [x] @zee-moz review & discuss
- [x] Revise and Refine
- [x] Create handout
- [x] Draft Slides in Google Slides

**Comment by auremoser** [comment]
well done!
githug
![](http://i.giphy.com/IdFSNW9m3hZ7O.gif)
