### ISSUE TITLE
Open Canvas

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/working-open-workshop#22]
Remix the [Lean Canvas](https://leanstack.com/lean-canvas) for use on open source projects

**Comment by abbycabs** [comment]
Page 1: Empty Canvas ([edit here](https://docs.google.com/drawings/d/1-7v3alEaJlcpbDySOgVOgIsRDV3-vZfYhd5KLXrvIlY/edit))
![open canvas - handout-1](https://cloud.githubusercontent.com/assets/617994/12700082/f809ef2c-c7a1-11e5-8de4-15eda3bd3f58.png)

Page 2: Instructions ([edit here](https://docs.google.com/a/mozilla.com/drawings/d/1nURelUHOSOUP6f2yRyGSp2hn4vVz9vQO7uSom1Ma-2o/edit?usp=sharing))
![open canvas - handout-1](https://cloud.githubusercontent.com/assets/617994/12700083/0c95927a-c7a2-11e5-900c-9e238dc885f0.png)

PDF:
[Open Canvas - Handout-1.pdf](https://github.com/mozillascience/working-open-workshop/files/111117/Open.Canvas.-.Handout-1.pdf)

flag @zee-moz for review

**Comment by abbycabs** [comment]
**Introduction:** The Open Canvas helps you write down and organize things you already know about your project. This will give you a big picture view of what you're trying to accomplish. If you can't fill all the boxes in the time set for this exercise, don't worry! We'll spend time during the workshop fleshing out your project plan.

**Time to complete:** 30min or less

**Materials:** A printout of the canvas and a pen

**Comment by kaythaney** [comment]
this looks great, abby. thank you! worth flagging to david + simon? (or on the demos call when we get back?)

**Comment by abbycabs** [comment]
Badges example using this canvas:
https://docs.google.com/drawings/d/1dXtwrtcHstXWgynntzr4gfP6SoMtsUvFzwxsZrXFIkg/edit?usp=sharing

**Comment by auremoser** [comment]
well done @acabunoc!
githug
![](http://i.giphy.com/UVtNGSo2MmdUI.gif)
