### ISSUE TITLE
Contributor Guidelines Talk - Content

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#3]
- [x] Review [short talk guidelines](https://github.com/mozillascience/learning/blob/master/talk-guidelines.md) 
- [x] Post a link to your outline here! For review and discussion. If you're just getting started, just link to wherever you're working.
- [x] @zee-moz review & discuss
- [x] Revise and Refine
- [x] Create handout
- [x] Draft Slides in Google Slides

**Comment by auremoser** [comment]
Outline under "Contributorship" [here](https://public.etherpad-mozilla.org/p/WOW-contrib)

**Comment by auremoser** [comment]
Status update, working on breaking it down into simpler format based on feedback.

**Comment by auremoser** [comment]
Here's the [handout](https://github.com/mozillascience/working-open-workshop/blob/master/handouts/contributing.md), stay tuned for the presentation.

**Comment by auremoser** [comment]
Here's a sample of the presentation (for now): https://docs.google.com/presentation/d/1YZA8rvD2Ix4F7y4ck44XYwTlQZ_YkM4higpuwy5swy8/edit?usp=sharing

I willl update it throughout the day.

**Comment by auremoser** [comment]
Presentation with template: https://docs.google.com/presentation/d/1YZA8rvD2Ix4F7y4ck44XYwTlQZ_YkM4higpuwy5swy8/edit?usp=sharing

**Comment by auremoser** [comment]
closing to make room for participant issues :)
