### ISSUE TITLE
Help with Science Lab Contributor Guidelines

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#30]
Hi we need structure and edits to our guidelines. 
Great issue for newcomers! :+1:

**Comment by joeyklee** [comment]
Hey looks like something I can do. Im a native english speaker and can take a look.

**Comment by RaoOfPhysics** [comment]
:+1:

**Comment by zee-moz** [comment]
THanks Joey that's so great! Let me know if you need any help. I am here to mentor this first bug. :smile:
