### ISSUE TITLE
Research fox linking to the front page

### ISSUE THREAD

**Issue by betatim** [mozillascience/working-open-workshop#33]
The big research fox logo in the top left of pages like http://mozillascience.github.io/working-open-workshop/writing_readme/ could be a hyperlink to http://mozillascience.github.io/working-open-workshop/

It would make navigating around easier.

**Comment by auremoser** [comment]
Thanks @betatim! Fixed with the latest commit 5e3b7a6
Appreciate the good bug!

**Comment by betatim** [comment]
Whoop! I send :chocolate_bar: :tada:
