### ISSUE TITLE
Add a humans.txt file

### ISSUE THREAD

**Issue by kaythaney** [mozillascience/working-open-workshop#34]
@saallen and I are going to try to add a humans.txt file to the repo. 

:+1: :smile:

**Comment by Saallen** [comment]
Great- lets get crackin :fireworks:

**Comment by kaythaney** [comment]
[Here's an example!](http://humanstxt.org/humans.txt)

**Comment by stephwright** [comment]
There's a member of the Mozilla Science Lab Staff missing from humans.txt :crying_cat_face:

**Comment by kaythaney** [comment]
added! thanks for the flag!

On Fri, Feb 5, 2016 at 4:22 PM, Stephanie Wright notifications@github.com
wrote:

> There's a member of the Mozilla Science Lab Staff missing from humans.txt [image:
> :crying_cat_face:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/working-open-workshop/issues/34#issuecomment-180398869
> .

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by stephwright** [comment]
:smile_cat:

**Comment by auremoser** [comment]
well done!!

**githug**

![](http://i.giphy.com/nu81tqIAUO8Le.gif)

**Comment by kaythaney** [comment]
these githugs are g-reeeeattttt!

sent on the move. apologies for typos.
