### ISSUE TITLE
GitHub for Newbies Talk - Content

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#4]
- [x] Review [short talk guidelines](https://github.com/mozillascience/learning/blob/master/talk-guidelines.md) 
- [x] Post a link to your outline here! For review and discussion. If you're just getting started, just link to wherever you're working.
- [x] @zee-moz review & discuss
- [x] Revise and Refine
- [x] Create handout
- [x] Draft Slides in Google Slides

@joeyklee @zee-moz helping!

**Comment by arlissc** [comment]
@zee-moz - thank you ...

**Comment by zee-moz** [comment]
We are working here: 
https://public.etherpad-mozilla.org/p/sciencelab-WOW-github

but a big chunk of other notes live here:
https://public.etherpad-mozilla.org/p/github101-planning
will fold in @auremoser work here: 
"Github Netiquette": https://public.etherpad-mozilla.org/p/WOW-contrib

**Comment by auremoser** [comment]
Thanks @zee-moz , no pressure, we can always make it another lesson, or a blog post if you think that suits the netiquette material better.

**Comment by zee-moz** [comment]
Now with Foxes!
![quickfox_bigbluefox](https://cloud.githubusercontent.com/assets/13855390/12650493/0ae2b130-c5b1-11e5-893c-f0bb84ed293d.png)

**Comment by auremoser** [comment]
adorbz!

**Comment by auremoser** [comment]
this was great, heard a lot of lovely feedback today on the demo!
**githug**
![](http://i.giphy.com/8FnZtdlK1k3Ly.gif)
