### ISSUE TITLE
The Open Web Stretch

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/working-open-workshop#42]
From Sara, as presented at #mozlando w/ EOY fundraising modifications (changed to grants)

---

Reaching for all of our open source dreams (arms up)
Reaching the grassroots (reach toes)
Come back up in the blowing of the winds of change (arms back and forth)
Reach out and shake the money tree in time for grant applications (arms forward, shake imaginary tree)
Lean left to avoid the NSA (hands on hips, lean left)
Lean right to avoid the NSA (hands on hips, lean right)
Go all around to avoid the NSA (hands on hips, lean all around)

**Comment by stephwright** [comment]
:raised_hands:

**Comment by katjaq** [comment]
waaaaa!!! awesome!!! \\ö//
