### ISSUE TITLE
Advanced GitHub Short Talk - Content

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#5]
- [x] Review short talk guidelines
- [x]    Post a link to your outline here! For review and discussion. If you're just getting started, just link to wherever you're working.
- [x]    @zee-moz review & discuss
- [ ]     Revise and Refine

@auremoser let's talk ASAP about what specifically this will cover!

**Comment by auremoser** [comment]
Under "Github Netiquette": https://public.etherpad-mozilla.org/p/WOW-contrib

**Comment by zee-moz** [comment]
As mentioned, we're going to fold this content into a single GitHub training, so moving the link to the Github for Newbs issue and closing this issue.
