### ISSUE TITLE
Code of Conduct Talk - Content

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#6]
- [x] Review short talk guidelines
- [x]  Post a link to your outline here! For review and discussion. If you're just getting started, just link to wherever you're working.
- [x]  @zee-moz review & discuss
- [x]   Revise and Refine
- [x] Create handout
- [x] Draft Slides in Google Slides

**Comment by kaythaney** [comment]
Took a stab at the resource portion here. Needs work / feedback. @zee-moz @auremoser - please feel free to hack! https://public.etherpad-mozilla.org/p/wow-contrib (line 325)

**Comment by kaythaney** [comment]
(cc @zee-moz)

Talk outline:

===0===

**INTROS (1 min)** 
- Aurelia - @auremoser 
- Kaitlin - @kaythaney

===1===

**ANECDOTE (2 min)**
- Aurelia: Girl Develop It
- Kaitlin: Conference experiences

===2===

**SETTING COMMUNITY NORMS (2 min)**
High level notes: 
- Signalling (+ modelling) what sort of community you want to cultivate 
- Just in case scenario
- Making others feel welcome 

Code of conducts serve a number of purposes. One is to help establish and clearly communicate the sort of behaviors prioritized in your project or at your event, like being respectful to others, or making sure your event is accessible to others. 

They also serve a functional need, in communicating to participants that should someone happen to violate the code, there’s a process and support from organizers in place. This alone signals that you’re serious about the well-being of your community members, and are taking steps to ensuring the event, project or workshop is an inviting, welcoming, and safe place. 

Think of communities you identify with, be they a set of friends, a group of peers, or an organization you feel a part of in some way. What sort of values or characteristics do you associate with being part of that community? What makes that a community you come back to, and how does it welcome others to participate?

Whether you’re leading a project or running an event, there are certain community dynamics that can help boost your work and provide a welcoming environment for others to join. We'll also walk you through how to create a code of conduct for your project / community WITH your community (and why that's important)

===3===

**WHAT TO DO IF SOMETHING HAPPENS (2 min)**
Tips on implementation / enforcement
- establish accountability among participants 
- designate a Safety / CoC committee (publicize their names, how to get in touch with them, perhaps photos/bios - it helps make them seem more approachable as well as identifiable)
- discuss with your community what the protocol is for flagging AND addressing an issue
- brainstorm behaviors you want to encourage, and ways you can help others feel safe and supported. 

Visibility (key takeaways):
- Post the CoC on your website
- Communicate at the beginning of your event / make sure it's discoverable and referenced in your project
- Delegate community members to serve as point people for conflict escalation, questions

Will words on paper alone stop people from being jerks? **Probably not.** 

But that doesn't mean you shouldn't still model best behavior or have a Code in place. 

===4===

**CREATING WITH (not for) YOUR COMMUNITY (3 min)**

We're firm believers that Code of Conducts - outside of their functional purpose - should begin as conversation starters. Use it to better understand the community dynamics members feel strongly about, and feed those comments into your CoC. 

Some guiding questions (lead in to activity):
- What core words would you associate with your community? 
- What behaviors do you want to encourage? .... and what do you want to discourage? 
- How does someone elevate an issue, should someone violate the code?
- What consequences are there for violating the code?
- How can you make others feel safe and supported?
- Who decides what does and does not violate the code? What's an example of how this might be done? 

===5===

**ACTIVITY**: http://mozillascience.github.io/working-open-workshop/code_of_conduct/

**Comment by auremoser** [comment]
thank you for rocking this! closing to make room for participant issues!
githug
![](http://i.giphy.com/11DvNsWoUQW1mU.gif)
