### ISSUE TITLE
Sprints and Events Talk - Content

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#7]
- [x] Review short talk guidelines
- [x]  Post a link to your outline here! For review and discussion. If you're just getting started, just link to wherever you're working.
- [x]  @zee-moz review & discuss
- [x]   Revise and Refine
- [x] Create handout
- [x] Draft Slides in Google Slides
  @mbonsma helping!

**Comment by arlissc** [comment]
@zee-moz - thanks so much.  working on this now ... will add link shortly.

**Comment by zee-moz** [comment]
Hi @arlissc and @mbonsma
I've been looking at the work you've been doing it https://docs.google.com/document/d/1NU5yfv4FF-_OeN-kw6zlmynteeLvZ9Geq34Lo-EB42s/edit... Thanks so much for this!

As we're creating a template for all the WOW learning resources, I went back and revised this facilitator tip sheet we made for the Summit last fall. Do either of you have changes, suggestions, additions to it? Feel free to edit to make it yours, and it can be part of the materials we point to during your talks...
https://public.etherpad-mozilla.org/p/sciencelab-facilitation-handout

Also, @arlissc can you point me to the current version of the sprint handbook? Thanks!!!

**Comment by mbonsma** [comment]
@zee-moz, this looks great! I added just one line to the event preparation section.

**Comment by auremoser** [comment]
well done all!
closing to make room for participant project issues.
thanks so much 
**githug**
![githug](http://i.giphy.com/lIgaClvpJdGwg.gif)
