### ISSUE TITLE
User Personas and Pathways Talk - Content

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#8]
- [x] Review short talk guidelines
- [x]  Post a link to your outline here! For review and discussion. If you're just getting started, just link to wherever you're working.
- [x]  @zee-moz review & discuss
- [x]   Revise and Refine
- [x] Create handout
- [x] Draft Slides in Google Slides
  @arlissc can you review & discuss with me?

**Comment by zee-moz** [comment]
talk and handout 
https://public.etherpad-mozilla.org/p/WOW-personas-pathways
https://public.etherpad-mozilla.org/p/WOW-personas-pathways-handout

**Comment by auremoser** [comment]
:) excellent
githug
![](http://i.giphy.com/zBMjpHeRDCMne.gif)
