### ISSUE TITLE
Data Use and Reuse Plan - Content

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/working-open-workshop#9]
- [x] Review short talk guidelines
- [x]  Post a link to your outline here! For review and discussion. If you're just getting started, just link to wherever you're working.
- [x]  @zee-moz review & discuss
- [x]   Revise and Refine
- [x] Create handout
- [x] Draft Slides in Google Slides
- [x] Present to @cbahlai OSRR class
- [x] Revise based on feedback and for more general audience at WOW
- [x] Review once more w/ @zee-moz 

@cbahlai is helping

**Comment by stephwright** [comment]
Google Doc w/ 10 min intro, followed by talk, followed by exercise.  Includes links to Quick Info sheets.  All in progress: https://docs.google.com/document/d/1SX_nhX8L1LvqSTsCnxv5x1bPVrcZRYIS3Zzl9oabS1c/edit

**Comment by zee-moz** [comment]
Adding Steph's data reuse plan template draft: https://docs.google.com/document/d/1pWqN2yCqD9Az-pVU4mCgM1g_ZCQxNrawF9EgyGqkeyM/edit

**Comment by stephwright** [comment]
Broke out workshop into separate components: (now in Markdown)
[15-20 min short talk](https://docs.google.com/document/d/1SX_nhX8L1LvqSTsCnxv5x1bPVrcZRYIS3Zzl9oabS1c/edit?usp=sharing)
[Exercise Handout](https://github.com/stephwright/OSRR_course/blob/master/04a_DataReusePlanExercise.md) 
[Data Reuse Plan Worksheet](https://github.com/stephwright/OSRR_course/blob/master/04b_Data_Reuse_Plan_Worksheet.md)
[Why Open Data Quick Info Sheet](https://github.com/stephwright/OSRR_course/blob/master/04c_OpenDataChallengesQuickInfoSheet.md)

**Comment by stephwright** [comment]
[Presentation](https://docs.google.com/a/mozilla.com/presentation/d/1vOWqL_7MUlEtN4eXQwf36wlmAhYEbhrRNQWp5D9uJws/edit?usp=sharing) in Google Slides for OSRR course.
- [x] talk needs to be shorter
- [x] revise to make more available for general use
- [x] de jargon a bit more

**Comment by stephwright** [comment]
Slides in new slide design template: https://docs.google.com/a/mozilla.com/presentation/d/1kZd-ZD5lru5a7jIbyi9q8cBYCCAKRnIBSRvixYFtoF0/edit?usp=sharing

**Comment by auremoser** [comment]
closing to make room for participant issues :) well done!

**Comment by auremoser** [comment]
![](http://i.giphy.com/apcKda9LY1XZS.gif)
